version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: payment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: payment_db
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: Payment@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - payment-network
    command: --default-authentication-plugin=mysql_native_password

  activemq:
    image: apache/activemq-classic:latest
    container_name:  payment-activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - payment-network

  payment-app:
    build: .
    container_name: payment-processing-system
    depends_on:
      - mysql
      - activemq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_db? allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: payment_user
      SPRING_DATASOURCE_PASSWORD: Payment@123
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    ports:
      - "8080:8080"
    networks:
      - payment-network
    restart: on-failure

networks:
  payment-network:
    driver: bridge

volumes:
  mysql-data: